# Dependabot Config
version: 2
updates:
  # Enable version updates for yarn
  - package-ecosystem: "npm"
    # Look for `package.json` and `yarn.lock` files in the `root` directory
    directory: "/"
    # Check for updates every day (weekdays)
    schedule:
      interval: "daily"
    # Raise pull requests for version updates against the `develop` branch
    target-branch: "develop"
    allow:
    # check only direct dependencies
      - dependency-type: "direct"
    labels:
      - "yarn dependencies"
